---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        state: latest

    - name: Upgrade all packages on servers
      apt: 
        upgrade: dist 
        force_apt_get: yes
    
    - name: Install ansible
      apt:
        name: ansible
        state: latest
        

